# Generated by Django 3.0.8 on 2021-08-31 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20210829_1520'),
    ]

    operations = [
        migrations.AddField(
            model_name='employees',
            name='email',
            field=models.EmailField(max_length=200, null=True, verbose_name='Email'),
        ),
        migrations.AddField(
            model_name='employees',
            name='salary',
            field=models.PositiveIntegerField(help_text='указывать сумму в сомах', null=True, verbose_name='Заработная плата'),
        ),
        migrations.AddField(
            model_name='employees',
            name='start_date',
            field=models.DateField(null=True, verbose_name='Дата входа на работу'),
        ),
    ]
