# Generated by Django 3.0.8 on 2021-09-04 17:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20210831_0822'),
    ]

    operations = [
        migrations.AddField(
            model_name='position',
            name='slug',
            field=models.SlugField(max_length=100, null=True, verbose_name='URL'),
        ),
        migrations.AlterField(
            model_name='employees',
            name='education',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.Education', verbose_name='Выбор учебного заведения'),
        ),
        migrations.AlterField(
            model_name='employees',
            name='position',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.Position', verbose_name='Выбор должности'),
        ),
    ]
