# Generated by Django 3.0.8 on 2021-09-04 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20210904_1705'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='position',
            name='slug',
        ),
        migrations.AddField(
            model_name='employees',
            name='url',
            field=models.SlugField(max_length=100, null=True, unique=True, verbose_name='Url'),
        ),
        migrations.AddField(
            model_name='position',
            name='url',
            field=models.SlugField(max_length=100, null=True, unique=True, verbose_name='URL'),
        ),
    ]
