# Generated by Django 3.0.8 on 2021-09-07 04:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20210904_1814'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employees',
            name='url',
        ),
        migrations.RemoveField(
            model_name='position',
            name='url',
        ),
    ]
