# Generated by Django 3.0.8 on 2021-09-20 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20210907_0441'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='education',
            options={'verbose_name': 'Образование', 'verbose_name_plural': 'Образовании'},
        ),
        migrations.AddField(
            model_name='employees',
            name='why',
            field=models.CharField(max_length=100, null=True, verbose_name='Причина увольнения'),
        ),
    ]
