# Generated by Django 3.0.8 on 2021-09-20 04:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20210920_0257'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dismissal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Причина увольнения')),
            ],
            options={
                'verbose_name': 'Причина',
                'verbose_name_plural': 'Причины',
            },
        ),
        migrations.AlterField(
            model_name='employees',
            name='why',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.Dismissal', verbose_name='Причина увольнения'),
        ),
    ]
